language: ruby
env:
  global:
    - GIT_COMMITTER_NAME='volanja'
    - GIT_COMMITTER_EMAIL='volaaanja@gmail.com'
    - GIT_AUTHOR_NAME='volanja'
    - GIT_AUTHOR_EMAIL='volaaanja@gmail.com'
    - secure: "rGFDxxSxbnM+a7lMAHWVIYHGfiG7wHx1zoEEC73FsnT+eB+8QOlwtDjUVzHgmhaO2FKXHARLkznEYZL8j4nCVW8faSQ0E9oUr+pHwSdKgcR77TkoWKTfhrZkJzgQBMfrQwIZVHHFQm532r8vr02LmBcHYs+Chzw5UfZxwHZ42WE="

branches:
  only:
    - gh-pages-build

rvm: 2.0.0
before_script:
    - git clone --quiet https://github.com/volanja/test-gh-pages_01.git build
    - pushd build
    - git checkout -b gh-pages-build
    - popd
script:
    - bundle exec middleman build
after_success:
    - git checkout -b gh-pages origin/gh-pages
    - ls -lta ./
　　- ls ./ | grep -v -E 'build' | xargs rm -rf
    - "mv build/* ./"
    - ls -lta ./
    - rm -rf build
    - ls -lta ./
    - git add *
    - git status
    - git commit -m 'Update'
    - echo $GH_TOKEN
    #- '[ "$TRAVIS_BRANCH" == "gh-pages" ] && [ $GH_TOKEN ] && git push --quiet https://$GH_TOKEN@github.com/volanja/test-gh-pages_01.git gh-pages'
    - 'git push --quiet https://$GH_TOKEN@github.com/volanja/test-gh-pages_01.git gh-pages'
