language: ruby
env:
  global:
    - GIT_COMMITTER_NAME='volanja'
    - GIT_COMMITTER_EMAIL='volaaanja@gmail.com'
    - GIT_AUTHOR_NAME='volanja'
    - GIT_AUTHOR_EMAIL='volaaanja@gmail.com'
    - secure: "DVAhVxOAoHQxbrsVqZF7QvZo4DZ13BDAn3Pzq22nQW+iXDD6xr6QNVJTNmHB/rVZk4rDGusWLQj4QP5opz5MMET4URHLRirbMN4kI3u+VRXP2A1ZIvUi5pGPJ77vx/mRbsU3yxqQWg4/p8Yhx/ZNmeb9PvZX6jhWjWNJsA2h12E="

branches:
  only:
    - gh-pages-build

rvm: 2.0.0
before_script:
    - cd ~/build/volanja
    - pwd
    - git clone --quiet -b gh-pages-build https://github.com/volanja/test-gh-pages_01.git gh-pages-build
script:
    - pwd
    - pushd gh-pages-build
    - bundle exec middleman build
after_success:
    - popd
    - pwd
    - git clone --quiet -b gh-pages https://github.com/volanja/test-gh-pages_01.git gh-pages
    - ls -lta ./
    - rm -rf ./gh-pages/*
    - cp -r ./gh-pages-build/build/* ./gh-pages/
    - ls -lta ./
    - cd ./gh-pages
    - git add *
    - git status
    - git commit -m 'Update'
    - 'git push --quiet https://$GH_TOKEN@github.com/volanja/test-gh-pages_01.git gh-pages 2> /dev/null' 
