language: ruby
env:
  global:
    - GIT_COMMITTER_NAME='volanja'
    - GIT_COMMITTER_EMAIL='volaaanja@gmail.com'
    - GIT_AUTHOR_NAME='volanja'
    - GIT_AUTHOR_EMAIL='volaaanja@gmail.com'
    - secure: "iHq8Nfc7qeISfMB+/wvH3/v6kay/kCcTAJMSE2VsdA03ZfEUHGnGNcKMYIFbKwRnfnjtwrG8t0GKnM5nK2bGgehrFQSWHE3UjKTJDs8lfwD0BeL3Umdg4/60LvuGp1nNPcU0P25iGa+iuq6L7wiDD1oB0LEE8RJ6KHYr1lx+mDg="

branches:
  only:
    - gh-pages-build

rvm: 2.0.0
before_script:
    - pwd
    - git clone --quiet -b gh-pages-build https://github.com/volanja/test-gh-pages_01.git build
script:
    - pwd
    - pushd build
    - bundle exec middleman build
    - mv build ../
after_success:
    - pwd
    - git clone --quiet -b gh-pages https://github.com/volanja/test-gh-pages_01.git gh-pages
    - ls -lta ./
    - rm -rf ./gh-pages/*
    - mv ./build/* ./gh-pages/
    - ls -lta ./
    - cd ./gh-pages
    - git add *
    - git status
    - git commit -m 'Update'
    #- '[ "$TRAVIS_BRANCH" == "gh-pages" ] && [ $GH_TOKEN ] && git push --quiet https://$GH_TOKEN@github.com/volanja/test-gh-pages_01.git gh-pages'
    #- 'git push --quiet https://$GH_TOKEN@github.com/volanja/test-gh-pages_01.git gh-pages'
